const clients = [
  {
    id: "1",
    clientName: "Oak",
    imageThumb: "/images/test.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "2",
    clientName: "Oak Teacher Hub",
    imageThumb: "/images/test.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "3",
    clientName: "Oak Classroom",
    imageThumb: "/images/test.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "4",
    clientName: "Pentland Disruption Lab",
    project: "Hayst",
    imageThumb: "/images/test.png",
    displayImage: "",
    ux: true,
    graphic: false,
    dev: true,
  },
  {
    id: "5",
    clientName: "Pentland Disruption Lab",
    project: "Toddl",
    imageThumb: "/images/test.png",
    displayImage: "",
    ux: true,
    graphic: false,
    dev: false,
  },
  {
    id: "6",
    clientName: "Edapt",
    imageThumb: "/images/test.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "7",
    clientName: "John Roberts",
    project: "Center for education and youth",
    agency: true,
    imageThumb: "/images/test.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "8",
    clientName: "Climbpass",
    imageThumb: "/images/test.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: false,
  },
  {
    id: "9",
    clientName: "Putty Studio",
    project: "Beginning Middle and End",
    imageThumb: "/images/test.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
  {
    id: "10",
    clientName: "Revere",
    project: "Beginning Middle and End",
    imageThumb: "/images/test.png",
    displayImage: "",
    ux: true,
    graphic: true,
    dev: true,
  },
];
export default clients;
